project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Representation & Electoral Systems"
  navbar:
    left:
      - text: About
        menu:
          - href: goals.qmd
            text: Our Goal
          - href: people.qmd
            text: People
      - href: events.qmd
        text: Events
      - href: resources.qmd
        text: Resources
      - href: connect.qmd
        text: Connect
  page-footer:
    background: "#084c50"
    foreground: "#ffffff"
    center: |
      Representation & Electoral Systems

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: true
    toc-title: "On this page"
    smooth-scroll: true
    link-external-newwindow: true
