project:
  type: website
  render:
    - "*.qmd"

website:
  title: "district-magnitude"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - text: About
        menu:
          - href: people.qmd
            text: People
      - href: resources.qmd
        text: Resources
      - href: connect.qmd
        text: Connect

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



